/*
 * OANDA v20 REST API
 *
 * The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * The version of the OpenAPI document: 3.0.25
 * Contact: api@oanda.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstrumentsInstrumentPositionBookGet200Response {
    #[serde(rename = "positionBook", skip_serializing_if = "Option::is_none")]
    pub position_book: Option<Box<models::PositionBook>>,
}

impl InstrumentsInstrumentPositionBookGet200Response {
    pub fn new() -> InstrumentsInstrumentPositionBookGet200Response {
        InstrumentsInstrumentPositionBookGet200Response {
            position_book: None,
        }
    }
}

