/*
 * OANDA v20 REST API
 *
 * The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * The version of the OpenAPI document: 3.0.25
 * Contact: api@oanda.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstrumentsInstrumentOrderBookGet200Response {
    #[serde(rename = "orderBook", skip_serializing_if = "Option::is_none")]
    pub order_book: Option<Box<models::OrderBook>>,
}

impl InstrumentsInstrumentOrderBookGet200Response {
    pub fn new() -> InstrumentsInstrumentOrderBookGet200Response {
        InstrumentsInstrumentOrderBookGet200Response {
            order_book: None,
        }
    }
}

