/*
 * OANDA v20 REST API
 *
 * The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * The version of the OpenAPI document: 3.0.25
 * Contact: api@oanda.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AccountFinancingMode : The financing mode of an Account
/// The financing mode of an Account
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AccountFinancingMode {
    #[serde(rename = "NO_FINANCING")]
    NoFinancing,
    #[serde(rename = "SECOND_BY_SECOND")]
    SecondBySecond,
    #[serde(rename = "DAILY")]
    Daily,

}

impl std::fmt::Display for AccountFinancingMode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::NoFinancing => write!(f, "NO_FINANCING"),
            Self::SecondBySecond => write!(f, "SECOND_BY_SECOND"),
            Self::Daily => write!(f, "DAILY"),
        }
    }
}

impl Default for AccountFinancingMode {
    fn default() -> AccountFinancingMode {
        Self::NoFinancing
    }
}

