/*
 * OANDA v20 REST API
 *
 * The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * The version of the OpenAPI document: 3.0.25
 * Contact: api@oanda.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClosePosition200Response {
    #[serde(rename = "longOrderCreateTransaction", skip_serializing_if = "Option::is_none")]
    pub long_order_create_transaction: Option<Box<models::MarketOrderTransaction>>,
    #[serde(rename = "longOrderFillTransaction", skip_serializing_if = "Option::is_none")]
    pub long_order_fill_transaction: Option<Box<models::OrderFillTransaction>>,
    #[serde(rename = "longOrderCancelTransaction", skip_serializing_if = "Option::is_none")]
    pub long_order_cancel_transaction: Option<Box<models::OrderCancelTransaction>>,
    #[serde(rename = "shortOrderCreateTransaction", skip_serializing_if = "Option::is_none")]
    pub short_order_create_transaction: Option<Box<models::MarketOrderTransaction>>,
    #[serde(rename = "shortOrderFillTransaction", skip_serializing_if = "Option::is_none")]
    pub short_order_fill_transaction: Option<Box<models::OrderFillTransaction>>,
    #[serde(rename = "shortOrderCancelTransaction", skip_serializing_if = "Option::is_none")]
    pub short_order_cancel_transaction: Option<Box<models::OrderCancelTransaction>>,
    /// The IDs of all Transactions that were created while satisfying the request.
    #[serde(rename = "relatedTransactionIDs", skip_serializing_if = "Option::is_none")]
    pub related_transaction_ids: Option<Vec<String>>,
    /// The ID of the most recent Transaction created for the Account
    #[serde(rename = "lastTransactionID", skip_serializing_if = "Option::is_none")]
    pub last_transaction_id: Option<String>,
}

impl ClosePosition200Response {
    pub fn new() -> ClosePosition200Response {
        ClosePosition200Response {
            long_order_create_transaction: None,
            long_order_fill_transaction: None,
            long_order_cancel_transaction: None,
            short_order_create_transaction: None,
            short_order_fill_transaction: None,
            short_order_cancel_transaction: None,
            related_transaction_ids: None,
            last_transaction_id: None,
        }
    }
}

