/*
 * OANDA v20 REST API
 *
 * The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * The version of the OpenAPI document: 3.0.25
 * Contact: api@oanda.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CloseTrade404Response {
    #[serde(rename = "orderRejectTransaction", skip_serializing_if = "Option::is_none")]
    pub order_reject_transaction: Option<Box<models::MarketOrderRejectTransaction>>,
    /// The ID of the most recent Transaction created for the Account. Only present if the Account exists.
    #[serde(rename = "lastTransactionID", skip_serializing_if = "Option::is_none")]
    pub last_transaction_id: Option<String>,
    /// The IDs of all Transactions that were created while satisfying the request. Only present if the Account exists.
    #[serde(rename = "relatedTransactionIDs", skip_serializing_if = "Option::is_none")]
    pub related_transaction_ids: Option<Vec<String>>,
    /// The code of the error that has occurred. This field may not be returned for some errors.
    #[serde(rename = "errorCode", skip_serializing_if = "Option::is_none")]
    pub error_code: Option<String>,
    /// The human-readable description of the error that has occurred.
    #[serde(rename = "errorMessage", skip_serializing_if = "Option::is_none")]
    pub error_message: Option<String>,
}

impl CloseTrade404Response {
    pub fn new() -> CloseTrade404Response {
        CloseTrade404Response {
            order_reject_transaction: None,
            last_transaction_id: None,
            related_transaction_ids: None,
            error_code: None,
            error_message: None,
        }
    }
}

