/*
 * OANDA v20 REST API
 *
 * The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * The version of the OpenAPI document: 3.0.25
 * Contact: api@oanda.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CloseTrade200Response {
    #[serde(rename = "orderCreateTransaction", skip_serializing_if = "Option::is_none")]
    pub order_create_transaction: Option<Box<models::MarketOrderTransaction>>,
    #[serde(rename = "orderFillTransaction", skip_serializing_if = "Option::is_none")]
    pub order_fill_transaction: Option<Box<models::OrderFillTransaction>>,
    #[serde(rename = "orderCancelTransaction", skip_serializing_if = "Option::is_none")]
    pub order_cancel_transaction: Option<Box<models::OrderCancelTransaction>>,
    /// The IDs of all Transactions that were created while satisfying the request.
    #[serde(rename = "relatedTransactionIDs", skip_serializing_if = "Option::is_none")]
    pub related_transaction_ids: Option<Vec<String>>,
    /// The ID of the most recent Transaction created for the Account
    #[serde(rename = "lastTransactionID", skip_serializing_if = "Option::is_none")]
    pub last_transaction_id: Option<String>,
}

impl CloseTrade200Response {
    pub fn new() -> CloseTrade200Response {
        CloseTrade200Response {
            order_create_transaction: None,
            order_fill_transaction: None,
            order_cancel_transaction: None,
            related_transaction_ids: None,
            last_transaction_id: None,
        }
    }
}

