/*
 * OANDA v20 REST API
 *
 * The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * The version of the OpenAPI document: 3.0.25
 * Contact: api@oanda.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigureAccount400Response {
    #[serde(rename = "clientConfigureRejectTransaction", skip_serializing_if = "Option::is_none")]
    pub client_configure_reject_transaction: Option<Box<models::ClientConfigureRejectTransaction>>,
    /// The ID of the last Transaction created for the Account.
    #[serde(rename = "lastTransactionID", skip_serializing_if = "Option::is_none")]
    pub last_transaction_id: Option<String>,
    /// The code of the error that has occurred. This field may not be returned for some errors.
    #[serde(rename = "errorCode", skip_serializing_if = "Option::is_none")]
    pub error_code: Option<String>,
    /// The human-readable description of the error that has occurred.
    #[serde(rename = "errorMessage", skip_serializing_if = "Option::is_none")]
    pub error_message: Option<String>,
}

impl ConfigureAccount400Response {
    pub fn new() -> ConfigureAccount400Response {
        ConfigureAccount400Response {
            client_configure_reject_transaction: None,
            last_transaction_id: None,
            error_code: None,
            error_message: None,
        }
    }
}

