/*
 * OANDA v20 REST API
 *
 * The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * The version of the OpenAPI document: 3.0.25
 * Contact: api@oanda.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FixedPriceOrderReason : The reason that the Fixed Price Order was created
/// The reason that the Fixed Price Order was created
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FixedPriceOrderReason {
    #[serde(rename = "PLATFORM_ACCOUNT_MIGRATION")]
    PlatformAccountMigration,

}

impl std::fmt::Display for FixedPriceOrderReason {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::PlatformAccountMigration => write!(f, "PLATFORM_ACCOUNT_MIGRATION"),
        }
    }
}

impl Default for FixedPriceOrderReason {
    fn default() -> FixedPriceOrderReason {
        Self::PlatformAccountMigration
    }
}

