/*
 * OANDA v20 REST API
 *
 * The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * The version of the OpenAPI document: 3.0.25
 * Contact: api@oanda.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetInstrumentPriceRange200Response {
    /// The list of prices that satisfy the request.
    #[serde(rename = "prices", skip_serializing_if = "Option::is_none")]
    pub prices: Option<Vec<models::Price>>,
}

impl GetInstrumentPriceRange200Response {
    pub fn new() -> GetInstrumentPriceRange200Response {
        GetInstrumentPriceRange200Response {
            prices: None,
        }
    }
}

