/*
 * OANDA v20 REST API
 *
 * The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * The version of the OpenAPI document: 3.0.25
 * Contact: api@oanda.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPrices200Response {
    /// The list of Price objects requested.
    #[serde(rename = "prices", skip_serializing_if = "Option::is_none")]
    pub prices: Option<Vec<models::ClientPrice>>,
    /// The list of home currency conversion factors requested. This field will only be present if includeHomeConversions was set to true in the request.
    #[serde(rename = "homeConversions", skip_serializing_if = "Option::is_none")]
    pub home_conversions: Option<Vec<models::HomeConversions>>,
    /// The DateTime value to use for the \"since\" parameter in the next poll request.
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<String>,
}

impl GetPrices200Response {
    pub fn new() -> GetPrices200Response {
        GetPrices200Response {
            prices: None,
            home_conversions: None,
            time: None,
        }
    }
}

