/*
 * OANDA v20 REST API
 *
 * The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * The version of the OpenAPI document: 3.0.25
 * Contact: api@oanda.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GuaranteedStopLossOrderEntryData : Details required by clients creating a Guaranteed Stop Loss Order
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GuaranteedStopLossOrderEntryData {
    /// The minimum distance allowed between the Trade's fill price and the configured price for guaranteed Stop Loss Orders created for this instrument. Specified in price units.
    #[serde(rename = "minimumDistance", skip_serializing_if = "Option::is_none")]
    pub minimum_distance: Option<String>,
    /// The amount that is charged to the account if a guaranteed Stop Loss Order is triggered and filled. The value is in price units and is charged for each unit of the Trade.
    #[serde(rename = "premium", skip_serializing_if = "Option::is_none")]
    pub premium: Option<String>,
    #[serde(rename = "levelRestriction", skip_serializing_if = "Option::is_none")]
    pub level_restriction: Option<Box<models::GuaranteedStopLossOrderLevelRestriction>>,
}

impl GuaranteedStopLossOrderEntryData {
    /// Details required by clients creating a Guaranteed Stop Loss Order
    pub fn new() -> GuaranteedStopLossOrderEntryData {
        GuaranteedStopLossOrderEntryData {
            minimum_distance: None,
            premium: None,
            level_restriction: None,
        }
    }
}

