/*
 * OANDA v20 REST API
 *
 * The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * The version of the OpenAPI document: 3.0.25
 * Contact: api@oanda.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GuaranteedStopLossOrderMode : The overall behaviour of the Account regarding guaranteed Stop Loss Orders.
/// The overall behaviour of the Account regarding guaranteed Stop Loss Orders.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum GuaranteedStopLossOrderMode {
    #[serde(rename = "DISABLED")]
    Disabled,
    #[serde(rename = "ALLOWED")]
    Allowed,
    #[serde(rename = "REQUIRED")]
    Required,

}

impl std::fmt::Display for GuaranteedStopLossOrderMode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Disabled => write!(f, "DISABLED"),
            Self::Allowed => write!(f, "ALLOWED"),
            Self::Required => write!(f, "REQUIRED"),
        }
    }
}

impl Default for GuaranteedStopLossOrderMode {
    fn default() -> GuaranteedStopLossOrderMode {
        Self::Disabled
    }
}

