/*
 * OANDA v20 REST API
 *
 * The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * The version of the OpenAPI document: 3.0.25
 * Contact: api@oanda.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InstrumentCommission : An InstrumentCommission represents an instrument-specific commission
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstrumentCommission {
    /// The commission amount (in the Account's home currency) charged per unitsTraded of the instrument
    #[serde(rename = "commission", skip_serializing_if = "Option::is_none")]
    pub commission: Option<String>,
    /// The number of units traded that the commission amount is based on.
    #[serde(rename = "unitsTraded", skip_serializing_if = "Option::is_none")]
    pub units_traded: Option<String>,
    /// The minimum commission amount (in the Account's home currency) that is charged when an Order is filled for this instrument.
    #[serde(rename = "minimumCommission", skip_serializing_if = "Option::is_none")]
    pub minimum_commission: Option<String>,
}

impl InstrumentCommission {
    /// An InstrumentCommission represents an instrument-specific commission
    pub fn new() -> InstrumentCommission {
        InstrumentCommission {
            commission: None,
            units_traded: None,
            minimum_commission: None,
        }
    }
}

