/*
 * OANDA v20 REST API
 *
 * The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * The version of the OpenAPI document: 3.0.25
 * Contact: api@oanda.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OpenTradeFinancing : OpenTradeFinancing is used to pay/collect daily financing charge for an open Trade within an Account
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpenTradeFinancing {
    /// The ID of the Trade that financing is being paid/collected for.
    #[serde(rename = "tradeID", skip_serializing_if = "Option::is_none")]
    pub trade_id: Option<String>,
    /// The amount of financing paid/collected for the Trade.
    #[serde(rename = "financing", skip_serializing_if = "Option::is_none")]
    pub financing: Option<String>,
}

impl OpenTradeFinancing {
    /// OpenTradeFinancing is used to pay/collect daily financing charge for an open Trade within an Account
    pub fn new() -> OpenTradeFinancing {
        OpenTradeFinancing {
            trade_id: None,
            financing: None,
        }
    }
}

