/*
 * OANDA v20 REST API
 *
 * The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * The version of the OpenAPI document: 3.0.25
 * Contact: api@oanda.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OrderIdentifier : An OrderIdentifier is used to refer to an Order, and contains both the OrderID and the ClientOrderID.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderIdentifier {
    /// The OANDA-assigned Order ID
    #[serde(rename = "orderID", skip_serializing_if = "Option::is_none")]
    pub order_id: Option<String>,
    /// The client-provided client Order ID
    #[serde(rename = "clientOrderID", skip_serializing_if = "Option::is_none")]
    pub client_order_id: Option<String>,
}

impl OrderIdentifier {
    /// An OrderIdentifier is used to refer to an Order, and contains both the OrderID and the ClientOrderID.
    pub fn new() -> OrderIdentifier {
        OrderIdentifier {
            order_id: None,
            client_order_id: None,
        }
    }
}

