/*
 * OANDA v20 REST API
 *
 * The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * The version of the OpenAPI document: 3.0.25
 * Contact: api@oanda.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Price : The Price representation
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Price {
    /// The Price's Instrument.
    #[serde(rename = "instrument", skip_serializing_if = "Option::is_none")]
    pub instrument: Option<String>,
    /// Flag indicating if the Price is tradeable or not
    #[serde(rename = "tradeable", skip_serializing_if = "Option::is_none")]
    pub tradeable: Option<bool>,
    /// The date/time when the Price was created.
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<String>,
    /// The base bid price as calculated by pricing.
    #[serde(rename = "baseBid", skip_serializing_if = "Option::is_none")]
    pub base_bid: Option<String>,
    /// The base ask price as calculated by pricing.
    #[serde(rename = "baseAsk", skip_serializing_if = "Option::is_none")]
    pub base_ask: Option<String>,
    /// The list of prices and liquidity available on the Instrument's bid side. It is possible for this list to be empty if there is no bid liquidity currently available for the Instrument in the Account.
    #[serde(rename = "bids", skip_serializing_if = "Option::is_none")]
    pub bids: Option<Vec<models::PriceBucket>>,
    /// The list of prices and liquidity available on the Instrument's ask side. It is possible for this list to be empty if there is no ask liquidity currently available for the Instrument in the Account.
    #[serde(rename = "asks", skip_serializing_if = "Option::is_none")]
    pub asks: Option<Vec<models::PriceBucket>>,
    /// The closeout bid price. This price is used when a bid is required to closeout a Position (margin closeout or manual) yet there is no bid liquidity. The closeout bid is never used to open a new position.
    #[serde(rename = "closeoutBid", skip_serializing_if = "Option::is_none")]
    pub closeout_bid: Option<String>,
    /// The closeout ask price. This price is used when an ask is required to closeout a Position (margin closeout or manual) yet there is no ask liquidity. The closeout ask is never used to open a new position.
    #[serde(rename = "closeoutAsk", skip_serializing_if = "Option::is_none")]
    pub closeout_ask: Option<String>,
}

impl Price {
    /// The Price representation
    pub fn new() -> Price {
        Price {
            instrument: None,
            tradeable: None,
            timestamp: None,
            base_bid: None,
            base_ask: None,
            bids: None,
            asks: None,
            closeout_bid: None,
            closeout_ask: None,
        }
    }
}

