/*
 * OANDA v20 REST API
 *
 * The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * The version of the OpenAPI document: 3.0.25
 * Contact: api@oanda.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SetOrderClientExtensions200Response {
    #[serde(rename = "orderClientExtensionsModifyTransaction", skip_serializing_if = "Option::is_none")]
    pub order_client_extensions_modify_transaction: Option<Box<models::OrderClientExtensionsModifyTransaction>>,
    /// The ID of the most recent Transaction created for the Account
    #[serde(rename = "lastTransactionID", skip_serializing_if = "Option::is_none")]
    pub last_transaction_id: Option<String>,
    /// The IDs of all Transactions that were created while satisfying the request.
    #[serde(rename = "relatedTransactionIDs", skip_serializing_if = "Option::is_none")]
    pub related_transaction_ids: Option<Vec<String>>,
}

impl SetOrderClientExtensions200Response {
    pub fn new() -> SetOrderClientExtensions200Response {
        SetOrderClientExtensions200Response {
            order_client_extensions_modify_transaction: None,
            last_transaction_id: None,
            related_transaction_ids: None,
        }
    }
}

