/*
 * OANDA v20 REST API
 *
 * The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * The version of the OpenAPI document: 3.0.25
 * Contact: api@oanda.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SetTradeDependentOrders400Response {
    #[serde(rename = "takeProfitOrderCancelRejectTransaction", skip_serializing_if = "Option::is_none")]
    pub take_profit_order_cancel_reject_transaction: Option<Box<models::OrderCancelRejectTransaction>>,
    #[serde(rename = "takeProfitOrderRejectTransaction", skip_serializing_if = "Option::is_none")]
    pub take_profit_order_reject_transaction: Option<Box<models::TakeProfitOrderRejectTransaction>>,
    #[serde(rename = "stopLossOrderCancelRejectTransaction", skip_serializing_if = "Option::is_none")]
    pub stop_loss_order_cancel_reject_transaction: Option<Box<models::OrderCancelRejectTransaction>>,
    #[serde(rename = "stopLossOrderRejectTransaction", skip_serializing_if = "Option::is_none")]
    pub stop_loss_order_reject_transaction: Option<Box<models::StopLossOrderRejectTransaction>>,
    #[serde(rename = "trailingStopLossOrderCancelRejectTransaction", skip_serializing_if = "Option::is_none")]
    pub trailing_stop_loss_order_cancel_reject_transaction: Option<Box<models::OrderCancelRejectTransaction>>,
    #[serde(rename = "trailingStopLossOrderRejectTransaction", skip_serializing_if = "Option::is_none")]
    pub trailing_stop_loss_order_reject_transaction: Option<Box<models::TrailingStopLossOrderRejectTransaction>>,
    /// The ID of the most recent Transaction created for the Account.
    #[serde(rename = "lastTransactionID", skip_serializing_if = "Option::is_none")]
    pub last_transaction_id: Option<String>,
    /// The IDs of all Transactions that were created while satisfying the request.
    #[serde(rename = "relatedTransactionIDs", skip_serializing_if = "Option::is_none")]
    pub related_transaction_ids: Option<Vec<String>>,
    /// The code of the error that has occurred. This field may not be returned for some errors.
    #[serde(rename = "errorCode", skip_serializing_if = "Option::is_none")]
    pub error_code: Option<String>,
    /// The human-readable description of the error that has occurred.
    #[serde(rename = "errorMessage", skip_serializing_if = "Option::is_none")]
    pub error_message: Option<String>,
}

impl SetTradeDependentOrders400Response {
    pub fn new() -> SetTradeDependentOrders400Response {
        SetTradeDependentOrders400Response {
            take_profit_order_cancel_reject_transaction: None,
            take_profit_order_reject_transaction: None,
            stop_loss_order_cancel_reject_transaction: None,
            stop_loss_order_reject_transaction: None,
            trailing_stop_loss_order_cancel_reject_transaction: None,
            trailing_stop_loss_order_reject_transaction: None,
            last_transaction_id: None,
            related_transaction_ids: None,
            error_code: None,
            error_message: None,
        }
    }
}

