/*
 * OANDA v20 REST API
 *
 * The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * The version of the OpenAPI document: 3.0.25
 * Contact: api@oanda.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StopOrderReason : The reason that the Stop Order was initiated
/// The reason that the Stop Order was initiated
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum StopOrderReason {
    #[serde(rename = "CLIENT_ORDER")]
    ClientOrder,
    #[serde(rename = "REPLACEMENT")]
    Replacement,

}

impl std::fmt::Display for StopOrderReason {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::ClientOrder => write!(f, "CLIENT_ORDER"),
            Self::Replacement => write!(f, "REPLACEMENT"),
        }
    }
}

impl Default for StopOrderReason {
    fn default() -> StopOrderReason {
        Self::ClientOrder
    }
}

