/*
 * OANDA v20 REST API
 *
 * The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * The version of the OpenAPI document: 3.0.25
 * Contact: api@oanda.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TradeStateFilter : The state to filter the Trades by
/// The state to filter the Trades by
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TradeStateFilter {
    #[serde(rename = "OPEN")]
    Open,
    #[serde(rename = "CLOSED")]
    Closed,
    #[serde(rename = "CLOSE_WHEN_TRADEABLE")]
    CloseWhenTradeable,
    #[serde(rename = "ALL")]
    All,

}

impl std::fmt::Display for TradeStateFilter {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Open => write!(f, "OPEN"),
            Self::Closed => write!(f, "CLOSED"),
            Self::CloseWhenTradeable => write!(f, "CLOSE_WHEN_TRADEABLE"),
            Self::All => write!(f, "ALL"),
        }
    }
}

impl Default for TradeStateFilter {
    fn default() -> TradeStateFilter {
        Self::Open
    }
}

