/*
 * OANDA v20 REST API
 *
 * The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * The version of the OpenAPI document: 3.0.25
 * Contact: api@oanda.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TradePl : The classification of TradePLs.
/// The classification of TradePLs.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TradePl {
    #[serde(rename = "POSITIVE")]
    Positive,
    #[serde(rename = "NEGATIVE")]
    Negative,
    #[serde(rename = "ZERO")]
    Zero,

}

impl std::fmt::Display for TradePl {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Positive => write!(f, "POSITIVE"),
            Self::Negative => write!(f, "NEGATIVE"),
            Self::Zero => write!(f, "ZERO"),
        }
    }
}

impl Default for TradePl {
    fn default() -> TradePl {
        Self::Positive
    }
}

