/*
 * OANDA v20 REST API
 *
 * The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * The version of the OpenAPI document: 3.0.25
 * Contact: api@oanda.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TrailingStopLossOrderReason : The reason that the Trailing Stop Loss Order was initiated
/// The reason that the Trailing Stop Loss Order was initiated
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TrailingStopLossOrderReason {
    #[serde(rename = "CLIENT_ORDER")]
    ClientOrder,
    #[serde(rename = "REPLACEMENT")]
    Replacement,
    #[serde(rename = "ON_FILL")]
    OnFill,

}

impl std::fmt::Display for TrailingStopLossOrderReason {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::ClientOrder => write!(f, "CLIENT_ORDER"),
            Self::Replacement => write!(f, "REPLACEMENT"),
            Self::OnFill => write!(f, "ON_FILL"),
        }
    }
}

impl Default for TrailingStopLossOrderReason {
    fn default() -> TrailingStopLossOrderReason {
        Self::ClientOrder
    }
}

