/*
 * OANDA v20 REST API
 *
 * The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * The version of the OpenAPI document: 3.0.25
 * Contact: api@oanda.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserInfoExternal : A representation of user information, as available to external (3rd party) clients.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserInfoExternal {
    /// The user's OANDA-assigned user ID.
    #[serde(rename = "userID", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<i32>,
    /// The country that the user is based in.
    #[serde(rename = "country", skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
    /// Flag indicating if the the user's Accounts adhere to FIFO execution rules.
    #[serde(rename = "FIFO", skip_serializing_if = "Option::is_none")]
    pub fifo: Option<bool>,
}

impl UserInfoExternal {
    /// A representation of user information, as available to external (3rd party) clients.
    pub fn new() -> UserInfoExternal {
        UserInfoExternal {
            user_id: None,
            country: None,
            fifo: None,
        }
    }
}

